name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
  pull_request:
    branches:
      - main
      - develop
      - "feature/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Test Application
      run: mvn test

  deploy_staging:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Staging
      run: |
        echo "Deploying to Staging"
        # Adicione aqui comandos de deployment para o ambiente de staging (ex: integração com Heroku, AWS, ou outro ambiente de staging)

  deploy_production:
    runs-on: ubuntu-latest
    needs: [build, deploy_staging]
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy to Production
      run: |
        echo "Deploying to Production"
        # Adicione aqui comandos de deployment para o ambiente de produção
